version: 2
jobs:
  lint:
    docker:
      - image: romanandreg/haskell-tools:latest
    environment:
      - TOOLS_DIR: /root/.local/bin
    steps:
      - checkout
      - run: "make -f make/tools.make lint"

  format:
    docker:
      - image: romanandreg/haskell-tools:latest
    environment:
      - TOOLS_DIR: /root/.local/bin
    steps:
      - checkout
      - run: "make -f make/tools.make format"

  sdist:
    docker:
      - image: romanandreg/stack:latest
    environment:
    steps:
      - checkout
      - restore_cache:
          key: build-cache-{{ checksum "etc/etc.cabal" }}-sdist
      - run: "make -f make/solver.make fix-solver && make test"
      - save_cache:
          key: build-cache-{{ checksum "etc/etc.cabal" }}-sdist
          paths:
            - /root/.stack
            - /root/.cabal
            - .stack-work

  lts-12:
    docker:
      - image: romanandreg/stack:latest
    environment:
      - STACK_ARGS: '--resolver lts-12'
      - CABAL_DIR: '/root/.local/bin'
    steps:
      - checkout
      - restore_cache:
          key: build-cache-{{ checksum "etc/etc.cabal" }}-lts11
      - run: "make -f make/solver.make fix-solver && make test"
      - save_cache:
          key: build-cache-{{ checksum "etc/etc.cabal" }}-lts11
          paths:
            - /root/.stack
            - /root/.ghc
            - .stack-work

  lts-11:
    docker:
      - image: romanandreg/stack:latest
    environment:
      - STACK_ARGS: '--resolver lts-11'
      - CABAL_DIR: '/root/.local/bin'
    steps:
      - checkout
      - restore_cache:
          key: build-cache-{{ checksum "etc/etc.cabal" }}-lts11
      - run: "make -f make/solver.make fix-solver && make test"
      - save_cache:
          key: build-cache-{{ checksum "etc/etc.cabal" }}-lts11
          paths:
            - /root/.stack
            - /root/.ghc
            - .stack-work

  lts-9:
    docker:
      - image: romanandreg/stack:latest
    environment:
      - STACK_ARGS: '--resolver lts-9'
      - CABAL_DIR: '/root/.local/bin'
    steps:
      - checkout
      - restore_cache:
          key: build-cache-{{ checksum "etc/etc.cabal" }}-lts9
      - run: "make -f make/solver.make fix-solver && make test"
      - save_cache:
          key: build-cache-{{ checksum "etc/etc.cabal" }}-lts9
          paths:
            - /root/.stack
            - /root/.ghc
            - .stack-work

  nightly:
    docker:
      - image: romanandreg/stack:latest
    environment:
      - STACK_ARGS: '--resolver nightly'
      - CABAL_DIR: '/root/.local/bin'
    steps:
      - checkout
      - restore_cache:
          key: build-cache-{{ checksum "etc/etc.cabal" }}-nightly
      # allow failure, as sometimes the nightly solver is "too new" and the
      # command doesn't work
      - run: "( make -f make/solver.make fix-solver && make test ) || true"
      - save_cache:
          key: build-cache-{{ checksum "etc/etc.cabal" }}-nightly
          paths:
            - /root/.stack
            - /root/.ghc
            - .stack-work

workflows:
  version: 2
  main:
    jobs:
      - sdist
      - lts-12
      - lts-11
      - lts-9
      - nightly
      - lint
      - format
